# Generated by Django 5.2.8 on 2025-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_documento_texto_extraido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='texto_extraido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
